spring:
  application:
    name: propintel-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/propintel
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ehddn1007!

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: false

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=600s

server:
  port: 8080

gemini:
  api-key: AQ.Ab8RN6K5_ivCvad37QXQoi469C3nFcErz1KAMuONxAt3uPgTmw

molit:
  api-key: b9d00d2fe6ff705588f80d61acf79e878cfd64d72bafe548032d40fed039d5a1
  base-url: https://apis.data.go.kr/1613000